export enum C {
  GAME_START = "game_start",
  GAME_UPDATE = "game_update",
  CHAT = "chat",
  PLAYER_DISCONNECT = "player_disconnect",
  GAME_END = "game_end",
  WEB_RTC_MEDIA_OFFER = "web_rtc_media_offer",
  WEB_RTC_MEDIA_ANSWER = "web_rtc_media_answer",
  WEB_RTC_ICE_CANDIDATE = "web_rtc_ice_candidate",
  WEB_RTC_REMOTE_PEER_ICE_CANDIDATE = "remote_peer_ice_candidate",
  RETRY_MATCHING = "retry_matching",
  REMOTE_IMAGE_URI = "remote_image_uri"
}

export const HALLS = ['Azad Hall of Residence',
  'B C Roy Hall of Residence',
  'B R Ambedkar Hall of Residence',
  'Gokhale Hall of Residence',
  'Homi J Bhabha Hall of Residence',
  'Jagadish Chandra Bose Hall of Residence',
  'Nehru Hall of Residence',
  'Lalbahadur Sastry Hall of Residence',
  'Lala Lajpat Rai Hall of Residence',
  'Madan Mohan Malviya Hall of Residence',
  'Megnad Saha Hall of Residence',
  'Mother Teresa Hall of Residence',
  'Nivedita Hall of Residence',
  'Patel Hall of Residence',
  'Radha Krishnan Hall of Residence',
  'Rani Laxmibai Hall of Residence',
  'Rajendra Prasad Hall of Residence',
  'Sam Hall of Residence',
  'Sarojini Naidu - Indira Gandhi Hall of Residence',
  'Vrsc Girls Tower',
  'Vidyasagar Hall of Residence',
  'Zakir Hussain Hall of Residence'
]

export const DEPARTMENTS = ['Aerospace Engineering',
  'Agricultural and Food Engineering',
  'Architecture and Regional Planning',
  'Bio Science',
  'Biotechnology',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Computer Science & Engineering',
  'Cryogenic  Engineering',
  'Deysarkar Centre of Excellence in Petroleum Engineering',
  'Electrical Engineering',
  'Electronics & Electrical Communication Engg.',
  'Energy Engineering',
  'Energy Science and Engineering',
  'Environmental Science and Engineering',
  'Exploration Geophysics',
  'Geology & Geophysics',
  'Humanities & Social Sciences',
  'Industrial and Systems Engineering',
  'Instrumentation Engineering',
  'Manufacturing Engineering',
  'Materials Science Centre',
  'Mathematics',
  'Mechanical Engineering',
  'Metallurgical & Materials Engineering',
  'Mining Engineering',
  'Nano Science and Technology',
  'Ocean Engg and Naval Architecture',
  'Physics',
  'Quality Engineering Design and Manufacturing',
  'Rajiv Gandhi School of Intellectual Property Law',
  'Statistics and Informatics',
  'Vinod Gupta School of Management'
]
